name: Notify Portfolio

on:
  push:
    branches:
      - dsaforge

jobs:
  notify-portfolio:
    runs-on: ubuntu-latest

    steps:
      - name: Send DSA update to Portfolio
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.PORTFOLIO_MESSAGE }}
          repository: shreyam91/portfolio
          event-type: dsa-updated
          client-payload: |
            {
              "repository": "shreyam91/Data_Structure_Algorithim",
              "branch": "dsaforge",
              "commit": "${{ github.sha }}"
            }
